# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ "prod" ]


  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app
            git pull
            docker build -t app:latest .
            docker container stop ezops-app
            docker container rm ezops-app
            docker run --name ezops-app --restart always -p 80:8000 app

