# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ "prod" ]


  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/app:latest
        
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
        
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app
        

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app
            git pull
            docker build -t app:latest .
            docker container stop ezops-app
            docker container rm ezops-app
            docker run -d --name ezops-app --restart always -p 80:8000 app
